env: dev
net: testnet
rocksdbfile: ./fullscan.tmp.db

queuebuffers:
  # 1024 * 1024
  step1out: 1048576
  cpcontrolfactor: 2
  mongoinfactor: 10
  last: 1024

workers:
  # these worker counts assume just a single but powerful rpc provider like suiscan being used
  step1: 2
  step2: 3
  mongo:

mongo:
  # you need to set this via ENV as it's the only way to set your credentials if we don't want to keep them in this file
  #uri: mongodb+srv://<user>:<pass>@sui-testnet.7b6tqsn.mongodb.net
  db: sui
  collectionbase: objects
  batchsize: 1024
  batchwaittimeoutms: 100
  retries: 2
  zstdlevel: 1

pulsar:
  url: pulsar+ssl://nonprod-9ce3148a-cd24-48d0-8c29-8e6561c3e44a.aws-euw1-snci-duck-prod-snc.aws.snio.cloud:6651
  issuer: https://auth.streamnative.cloud/
  # o-mvqin-testnet.json, base64-encoded
  # you probably want to override this via ENV
  # TODO discuss whether we should not include the testnet credentials here
  credentials: eyJ0eXBlIjoic25fc2VydmljZV9hY2NvdW50IiwiY2xpZW50X2lkIjoiUzNPUlZNc1VabDBaRUU3TnJjM3FJNzFNd1JlYm94bGEiLCJjbGllbnRfc2VjcmV0IjoiSkRDdjRyOUQzTWVwTzc5empuWVRBcWwwNkpYb3F1R3l5OVNUVDZna21xdTZOZG13ZUtESzVZVTNQTkFtNU5IdyIsImNsaWVudF9lbWFpbCI6InRlc3RuZXRAby1tdnFpbi5hdXRoLnN0cmVhbW5hdGl2ZS5jbG91ZCIsImlzc3Vlcl91cmwiOiJodHRwczovL2F1dGguc3RyZWFtbmF0aXZlLmNsb3VkLyJ9
  audience: urn:sn:pulsar:o-mvqin:nonprod
  topicbase: persistent://public/default/

sui:
  testnet:
    - url: https://rpc-testnet.suiscan.xyz:443
      name: suiscan
      objectsquerylimit: 50
      # slow!
#    - url: https://sui-testnet.nodeinfra.com:443
#      name: nodeinfra
#      objectsquerylimit: 50
  mainnet:
    - url: https://rpc-mainnet.suiscan.xyz:443
      name: suiscan
      objectsquerylimit: 50
  step1retries: 3
  step1retrytimeoutms: 500

log:
  # fancy some colors? - disable if redirect to file is intended
  ansi: true
  # base-line log level
  level: info
  # my_crate=info,my_crate::my_mod=debug,[my_span]=trace
  # see https://tracing.rs/tracing_subscriber/filter/struct.envfilter
  #filter:
