log:
  # fancy some colors? - disable if redirect to file is intended
  ansi: true
  # base-line log level
  level: info
  # my_crate=info,my_crate::my_mod=debug,[my_span]=trace
  # see https://tracing.rs/tracing_subscriber/filter/struct.envfilter
  #filter:

mongo:
  uri: "mongodb+srv://sui-devnet.gpf3cd1.mongodb.net/"
  database: "sui"
  objects:
    collection: "objects2"

sui:
  api:
    urls:
      - "https://sui-testnet.nodeinfra.com:443/"
      - "https://rpc-testnet.suiscan.xyz:443"
