app = "server-prod-mainnet"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "30s"

[http_service]
internal_port = 8000
force_https = true

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[experimental]
auto_rollback = true

[env]
APP_ENV = "prod"
APP_NET = "mainnet"
APP_MONGO_COLLECTIONBASE = "objects"

[build]
dockerfile = "Dockerfile"
