app = "server-prod-testnet"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "30s"

[http_service]
internal_port = 8000
force_https = true

[experimental]
auto_rollback = true

[env]
APP_ENV = "prod"
APP_NET = "testnet"
APP_MONGO_COLLECTIONBASE = "objects"
