name: (prod) (server) build & deploy
on:
  push:
    branches:
      - gha
    paths:
      - 'server/**'
      - 'macros/**'
      - 'config.yaml'
      - '!*.txt'
env:
  CRATE_DIR: server
  APP_BIN: server
  # XXX can't reference env context here, so we have to repeat ourselves
  IMAGE: ${{ github.repository }}/server
  TAG: gha
  REGISTRY: ghcr.io
  FLY_REGISTRY: registry.fly.io
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y -q clang protobuf-compiler
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-05-15
      - uses: mozilla-actions/sccache-action@v0.0.3
        with:
          version: v0.4.2
      - run: cargo build --bin ${{ env.APP_BIN }}
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
      - run: mkdir binaries && mv target/*/${{ env.APP_BIN }} binaries/
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v2
        with:
          # see: https://github.com/superfly/flyctl/issues/104#issuecomment-614973806
          registry: ${{ env.FLY_REGISTRY }}
          username: ${{ secrets.FLY_TOKEN }}
          password: x
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.IMAGE }}
      # temp workaround | from: https://github.com/docker/build-push-action#git-context
      # (not sure we need this, but including just in case)
      # Setting up Docker Buildx with docker-container driver is required
      # at the moment to be able to use a subdirectory with Git context
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          build-args: BIN=${{ env.APP_BIN }}
          build-contexts: binaries=binaries
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.FLY_REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy_testnet:
    name: deploy testnet
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: testnet
        run: flyctl deploy -i ${{ env.FLY_REGISTRY }}/${{ env.IMAGE }}:gha ${{ env.CRATE_DIR }} -c fly-prod-testnet.toml
  deploy_mainnet:
    name: deploy mainnet
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: mainnet
        run: flyctl deploy -i ${{ env.FLY_REGISTRY }}/${{ env.IMAGE }}:gha ${{ env.CRATE_DIR }} -c fly-prod-mainnet.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
